redis:
    address: redis:6379
    username: ""
    password: redispassword
    db: 0
    use_tls: false
api_key: devkey
api_secret: secret
ws_url: ws://openvidu:7880
rtmp_port: 1935
whip_port: 8085
http_relay_port: 9090
health_port: 9091
logging:
    json: false
    level: ""
development: false
rtc_config:
    udp_port: 7895
