services:

  generate-scripts:
    image: curlimages/curl:8.15.0
    entrypoint: ["/bin/sh", "-c"]
    restart: "no"
    user: root
    volumes:
      - scripts:/scripts
      - config:/config
    command:
      - |
        set -e
        # Check if /scripts and /config are empty, if not, skip script generation
        if [ "$(ls -A /scripts)" ] && [ "$(ls -A /config)" ]; then
          echo "/config and /scripts are not empty, skipping script generation."
          exit 0
        fi
        echo "Generating scripts..."
        echo "$${SETUP_SCRIPT}" > /scripts/setup.sh
        echo "$${UTILS_SCRIPT}" > /scripts/utils.sh
        echo "$${READY_CHECK_ENTRYPOINT}" > /scripts/entrypoint_ready_check.sh
        echo "$${CADDY_ENTRYPOINT}" > /scripts/entrypoint_caddy.sh
        echo "$${OPENVIDU_ENTRYPOINT}" > /scripts/entrypoint_openvidu.sh
        echo "$${OPENVIDU_MEET_ENTRYPOINT}" > /scripts/entrypoint_openvidu_meet.sh
        echo "Downloading default config files..."
        base_url="https://raw.githubusercontent.com/OpenVidu/openvidu-local-deployment/refs/heads/$$OPENVIDU_LOCAL_DEPLOYMENT_BRANCH/community"
        curl -sS -o /config/livekit.yaml "$${base_url}/livekit.yaml"
        curl -sS -o /config/ingress.yaml "$${base_url}/ingress.yaml"
        curl -sS -o /config/egress.yaml "$${base_url}/egress.yaml"
        echo "Setting permissions..."
        chmod +x /scripts/setup.sh
        chmod +x /scripts/utils.sh
        chmod +x /scripts/entrypoint_ready_check.sh
        chmod +x /scripts/entrypoint_caddy.sh
        chmod +x /scripts/entrypoint_openvidu.sh
        chmod +x /scripts/entrypoint_openvidu_meet.sh
    environment:
      OPENVIDU_LOCAL_DEPLOYMENT_BRANCH: feature/meet-local-compose-app
      SETUP_SCRIPT: |
        #!/bin/sh
        echo "Setting up directories and permissions..."
        mkdir -p /minio/data/
        mkdir -p /mongo/data/
        mkdir -p /egress/home/egress
        chown 1001:1001 /minio /minio/data
        chown 1001:1001 /mongo /mongo/data
        chown 1001:1001 /egress
        chown 1001:1001 /egress/home
        chown 1001:1001 /egress/home/egress
        echo "Setup complete."
      UTILS_SCRIPT: |
        #!/bin/sh
        LAN_DOMAIN=openvidu-local.dev
        if [ "$$LAN_PRIVATE_IP" != "" ]; then
            export USE_HTTPS=true
            export LAN_MODE=true
        else
            export USE_HTTPS=false
            export LAN_MODE=false
        fi
        echo "Using LAN_PRIVATE_IP: $${LAN_PRIVATE_IP:-none}"
        echo "Using USE_HTTPS: $${USE_HTTPS}"
        echo "Using LAN_MODE: $${LAN_MODE}"
        getDeploymentUrl() {
            schema="$${1:-http}"
            URL="$$schema://localhost:7880"
            if [ "$${USE_HTTPS}" = 'true' ]; then
                URL="$${schema}s://localhost:7443"
            fi
            if [ "$${LAN_MODE}" = 'true' ]; then
                LAN_DOMAIN=$${LAN_DOMAIN:-"openvidu-local.dev"}
                if [ "$$LAN_PRIVATE_IP" != 'none' ] && [ "$${LAN_DOMAIN}" = 'openvidu-local.dev' ]; then
                    # Replace dots with dashes
                    LAN_DOMAIN="$$(echo "$$LAN_PRIVATE_IP" | sed 's/\./-/g').openvidu-local.dev"
                fi
                URL="$${schema}s://$${LAN_DOMAIN}:7443"
            fi
            echo "$$URL"
        }
      READY_CHECK_ENTRYPOINT: |
        #!/bin/sh
        set -e
        export LAN_DOMAIN=openvidu-local.dev
        if [ "$$LAN_PRIVATE_IP" != "" ]; then
          export USE_HTTPS=true
          export LAN_MODE=true
        else
          export USE_HTTPS=false
          export LAN_MODE=false
        fi
        echo "Using LAN_PRIVATE_IP: $${LAN_PRIVATE_IP:-none}"
        echo "Using LAN_DOMAIN: $${LAN_DOMAIN}"
        echo "Using USE_HTTPS: $${USE_HTTPS}"
        echo "Using LAN_MODE: $${LAN_MODE}"
        /bin/operator
      CADDY_ENTRYPOINT: |
        #!/bin/sh
        set -e
        export LAN_DOMAIN=openvidu-local.dev
        if [ "$$LAN_PRIVATE_IP" != "" ]; then
          export USE_HTTPS=true
          export LAN_MODE=true
        else
          export USE_HTTPS=false
          export LAN_MODE=false
        fi
        echo "Using LAN_PRIVATE_IP: $${LAN_PRIVATE_IP:-none}"
        echo "Using LAN_DOMAIN: $${LAN_DOMAIN}"
        echo "Using USE_HTTPS: $${USE_HTTPS}"
        echo "Using LAN_MODE: $${LAN_MODE}"
        /entrypoint.sh /usr/bin/caddy run --config /config/caddy/Caddyfile
      OPENVIDU_ENTRYPOINT: |
        #!/bin/sh
        set -e
        if [ "$$LAN_PRIVATE_IP" != "" ]; then
            echo "Using as NODE_IP: $$LAN_PRIVATE_IP"
            export NODE_IP="$$LAN_PRIVATE_IP"
        fi
        ./livekit-server "$@"
      OPENVIDU_MEET_ENTRYPOINT: |
        #!/bin/bash
        . /scripts/utils.sh

        URL=$(getDeploymentUrl ws)
        export LIVEKIT_URL="$${URL}"

        /usr/local/bin/entrypoint.sh

  setup:
    image: docker.io/busybox:1.37.0
    platform: linux/amd64
    container_name: setup
    restart: "no"
    volumes:
      - minio-data:/minio
      - mongo-data:/mongo
      - egress-data:/egress
      - scripts:/scripts/
    user: root
    depends_on:
      generate-scripts:
        condition: service_completed_successfully
    command: /bin/sh /scripts/setup.sh
